fun inc(x) {
  try(, catch(clojure_lang_ExceptionInfo, e, if _getMessage(e) == "return" { [value, ex_data(e)] }))
}
fun main() {
  let k = 2
  print(inc(3))
}
main()
