run: exit status 1
[0m[1m[31merror[0m: Uncaught (in promise) Error: malus_law test3 failed
function _panic(msg: any): never { throw new Error(String(msg)); }
[0m[31m                                         ^[0m
    at [0m[1m[3m_panic[0m ([0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/malus_law.ts[0m:[0m[33m111[0m:[0m[33m42[0m)
    at [0m[1m[3mtest_malus_law[0m ([0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/malus_law.ts[0m:[0m[33m43[0m:[0m[33m5[0m)
    at [0m[1m[3mmain[0m ([0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/malus_law.ts[0m:[0m[33m56[0m:[0m[33m3[0m)
    at [0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/malus_law.ts[0m:[0m[33m116[0m:[0m[33m3[0m
    at [0m[36mfile:///workspace/mochi/tests/algorithms/x/TypeScript/physics/malus_law.ts[0m:[0m[33m128[0m:[0m[33m2[0m
